#!url=http://script.hub/file/_start_/https://raw.githubusercontent.com/FoKit/Scripts/main/rewrite/get_jd_wskey.sgmodule/_end_/get_jd_wskey.sgmodule?type=surge-module&target=shadowrocket-module&del=true
#!name=京东 WSKEY
#!desc=自动抓取京东WSKEY, 仅支持 Surge, 未经允许请勿使用。（自动上车）

[Script]
京东 WSKEY = type=http-request, pattern=https:\/\/blackhole\.m\.jd\.com\/getinfo, script-path=https://raw.githubusercontent.com/FoKit/Scripts/main/scripts/get_jd_wskey.js, max-size=0, script-update-interval=0, timeout=30

京东 PIN = type=http-request, pattern=https:\/\/perf\.m\.jd\.com\/app_monitor\/\w{1,}\/getRule, script-path=https://raw.githubusercontent.com/FoKit/Scripts/main/scripts/get_jd_wskey.js, max-size=0, script-update-interval=0, timeout=30

[MITM]
hostname = %APPEND% blackhole.m.jd.com, perf.m.jd.com

