#!url=http://script.hub/file/_start_/https://raw.githubusercontent.com/mieqq/mieqq/master/skip-proxy-lists.sgmodule/_end_/skip-proxy-lists.sgmodule?type=surge-module&target=shadowrocket-module&del=true
#!name=Skip Proxy And Real-IP Lists
#!desc=跳过部分应用的代理检测

[General]
skip-proxy = %APPEND% download1.bankcomm.cn:*, monitor.bankcomm.cn:*, mobile.bankcomm.cn:*, www.qq.com, www.baidu.com, yunbusiness.ccb.com, wxh.wo.cn, gate.lagou.com, www.abchina.com.cn, www.shanbay.com, login-service.mobile-bank.psbc.com, mobile-bank.psbc.com, id6.me

always-real-ip = %APPEND% easy-login.10099.com.cn, *-update.xoyocdn.com, id6.me, open.e.189.cn

