#!url=https://raw.githubusercontent.com/sooyaaabo/Egern/main/module/CoolApk.module
#!name=酷安
#!desc=过滤酷安广告
#!author=RuCu6[https://github.com/RuCu6], ZenmoFeiShi[https://github.com/ZenmoFeiShi], 可莉🅥[https://github.com/luestr/ProxyResource/blob/main/README.md]
#!icon=https://raw.githubusercontent.com/sooyaaabo/Loon/main/Icon/App-Icon/CoolApk.png
#!openUrl=https://apps.apple.com/app/id1422581869
#!tag=去广告
#!homepage=https://github.com/sooyaaabo/Egern
#!date=2025-01-01 00:00

[URL Rewrite]
^https:\/\/api\.coolapk\.com\/v6\/search\?.*type=hotSearch - reject-dict

[Script]
# 可莉🅥
移除酷安广告 = type=http-response, pattern=^https:\/\/api\.coolapk\.com\/v6\/(?:feed\/detail|feed\/replyList|page\/dataList|main\/dataList|main\/indexV8|main\/init), script-path=https://kelee.one/Resource/Script/CoolApk/CoolApk_remove_ads.js, requires-body=true

# ZenmoFeiShi
移除酷安广告 = type=http-response, pattern=^https:\/\/api\.coolapk\.com\/v6\/main\/init, script-path=https://raw.githubusercontent.com/ZenmoFeiShi/Qx/main/KuAn.js, requires-body=true

移除酷安广告 = type=http-response, pattern=^https:\/\/api\.coolapk\.com\/v6\/main\/indexV8, script-path=https://raw.githubusercontent.com/ZenmoFeiShi/Qx/main/KuAn.js, requires-body=true

移除酷安广告 = type=http-response, pattern=^https:\/\/api\.coolapk\.com\/v6\/page\/dataList, script-path=https://raw.githubusercontent.com/ZenmoFeiShi/Qx/main/KuAn.js, requires-body=true

移除酷安广告 = type=http-response, pattern=^https:\/\/api\.coolapk\.com\/v6\/account\/loadConfig\?key=my_page_card_config, script-path=https://raw.githubusercontent.com/ZenmoFeiShi/Qx/main/KuAn.js, requires-body=true

[MITM]
hostname = %APPEND% api.coolapk.com